### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by InfernalHeir** [jito-labs/mev-bot#10]
Error: 12 UNIMPLEMENTED: subscribe_mempool is deprecated
    at callErrorFromStatus (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/client.ts:611:51)
    at Object.onReceiveStatus (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/client.ts:594:42)
    at ServiceClientImpl.subscribeMempool (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at SearcherClient.programUpdates (/mnt/c/Users/bhupe/jito-mev/node_modules/jito-ts/src/sdk/block-engine/searcher.ts:171:19)
    at programUpdates.next (<anonymous>)
    at /mnt/c/Users/bhupe/jito-mev/src/index.ts:27:31
    at Generator.next (<anonymous>)
    at /mnt/c/Users/bhupe/jito-mev/src/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/bhupe/jito-mev/src/index.ts:4:12)
    at main (/mnt/c/Users/bhupe/jito-mev/src/index.ts:27:12) {
  code: 12,
  details: 'subscribe_mempool is deprecated',
  metadata: Metadata {
    internalRepr: Map(5) {
      'content-type' => [Array],
      'content-length' => [Array],
      'date' => [Array],
      'x-envoy-upstream-service-time' => [Array],
      'server' => [Array]
    },
    options: {}
  }
}
AbortError: The operation was aborted
    at Object.destroyer (node:internal/streams/destroy:327:11)
    at createAsyncIterator (node:internal/streams/readable:1399:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SearcherClient.programUpdates (/mnt/c/Users/bhupe/jito-mev/node_modules/jito-ts/src/sdk/block-engine/searcher.ts:181:22) {
  code: 'ABORT_ERR'
}
/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/call.ts:82
  const error = new Error(message);
                ^
Error: 12 UNIMPLEMENTED: subscribe_mempool is deprecated
    at callErrorFromStatus (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/client.ts:611:51)
    at Object.onReceiveStatus (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/client.ts:594:42)
    at ServiceClientImpl.subscribeMempool (/mnt/c/Users/bhupe/jito-mev/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at SearcherClient.programUpdates (/mnt/c/Users/bhupe/jito-mev/node_modules/jito-ts/src/sdk/block-engine/searcher.ts:171:19)
    at programUpdates.next (<anonymous>)
    at /mnt/c/Users/bhupe/jito-mev/src/index.ts:27:31
    at Generator.next (<anonymous>)
    at /mnt/c/Users/bhupe/jito-mev/src/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/bhupe/jito-mev/src/index.ts:4:12)
    at main (/mnt/c/Users/bhupe/jito-mev/src/index.ts:27:12) {
  code: 12,
  details: 'subscribe_mempool is deprecated',
  metadata: Metadata {
    internalRepr: Map(5) {
      'content-type' => [Array],
      'content-length' => [Array],
      'date' => [Array],
      'x-envoy-upstream-service-time' => [Array],
      'server' => [Array]
    },
    options: {}
  }
}

**Comment by gladwinput** [comment]
mempool was removed to disrupt sandwich bots - the only way around this is to create your own validator and connect to it using geyser

**Comment by YG-95** [comment]
Will it not work through rpc node either?
