### ISSUE TITLE
The endpoint can only be paired with an `https.Agent`. You have, instead, supplied an `http.Agent` through `httpAgent`

### ISSUE THREAD

**Issue by ImRajdeepB** [jito-labs/mev-bot#4]
When I run `yarn start`, I'm facing this error:

```
/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/node_modules/@solana/web3.js/lib/index.cjs.js:6192
          throw new Error('The endpoint `' + url + '` can only be paired with an `https.Agent`. You have, instead, supplied an ' + '`http.Agent` through `httpAgent`.');
                ^

Error: The endpoint `https://frankfurt.mainnet.rpc.jito.wtf` can only be paired with an `https.Agent`. You have, instead, supplied an `http.Agent` through `httpAgent`.
    at createRpcClient (/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/node_modules/@solana/web3.js/lib/index.cjs.js:6192:17)
    at new Connection (/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/node_modules/@solana/web3.js/lib/index.cjs.js:7132:23)
    at new JitoRpcConnection (/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/dist/sdk/rpc/connection.js:258:9)
    at file:///Users/rajdeep/dev/jito-mev-bot/build/src/clients/rpc.js:122:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by amer2040** [comment]
add this in rpc.ts

const agent = new https.Agent({
  keepAlive: true,
  maxSockets: 512,
});

if (RPC_REQUESTS_PER_SECOND > 0) {
  connection = new Connection(RPC_URL, {
    httpAgent: agent,
    disableRetryOnRateLimit: true,
    commitment: 'processed',
    fetch: coalesceFetch(),
  });
} else {
  connection = new Connection(RPC_URL, {
    httpAgent: agent,
    disableRetryOnRateLimit: true,
    commitment: 'processed',
  });
}

**Comment by amer2040** [comment]
> When I run `yarn start`, I'm facing this error:
> 
> ```
> /Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/node_modules/@solana/web3.js/lib/index.cjs.js:6192
>           throw new Error('The endpoint `' + url + '` can only be paired with an `https.Agent`. You have, instead, supplied an ' + '`http.Agent` through `httpAgent`.');
>                 ^
> 
> Error: The endpoint `https://frankfurt.mainnet.rpc.jito.wtf` can only be paired with an `https.Agent`. You have, instead, supplied an `http.Agent` through `httpAgent`.
>     at createRpcClient (/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/node_modules/@solana/web3.js/lib/index.cjs.js:6192:17)
>     at new Connection (/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/node_modules/@solana/web3.js/lib/index.cjs.js:7132:23)
>     at new JitoRpcConnection (/Users/rajdeep/dev/jito-mev-bot/node_modules/jito-ts/dist/sdk/rpc/connection.js:258:9)
>     at file:///Users/rajdeep/dev/jito-mev-bot/build/src/clients/rpc.js:122:18
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
>     at async loadESM (node:internal/process/esm_loader:91:5)
>     at async handleMainPromise (node:internal/modules/run_main:65:12)
> ```

add this code in rpc.ts file

const agent = new https.Agent({
  keepAlive: true,
  maxSockets: 512,
});

if (RPC_REQUESTS_PER_SECOND > 0) {
  connection = new Connection(RPC_URL, {
    httpAgent: agent,
    disableRetryOnRateLimit: true,
    commitment: 'processed',
    fetch: coalesceFetch(),
  });
} else {
  connection = new Connection(RPC_URL, {
    httpAgent: agent,
    disableRetryOnRateLimit: true,
    commitment: 'processed',
  });
}

**Comment by mazgalesc** [comment]
read the error again pls.. you will figure it out

**Comment by Wiger123** [comment]
I meet the same problem, it seems like mev-bot misunderstood the url of https to http

**Comment by staccDOTsol** [comment]
I meet the same broblem

**Comment by akSolkhatri** [comment]
Anyone got the solution?

**Comment by zzxn** [comment]
> Anyone got the solution?

Just delete the code that checks agent type...

**Comment by smilesmile191** [comment]
> read the error again pls.. you will figure it out

Please tell me how to solve it

**Comment by yahdielo** [comment]
just change the endpoint to https://frankfurt.mainnet.rpc.jito.wtf to http:
that should solve the problem, also make sure to have geyser access token

**Comment by yahdielo** [comment]
> > read the error again pls.. you will figure it out
> 
> Please tell me how to solve it

change the  endpoint https: to http:
that should do it.

**Comment by fabiankaeser82** [comment]
Please can someone help me tu run this ?

**Comment by Whitence** [comment]
easy，just comment out the agent

like this:

if (RPC_REQUESTS_PER_SECOND > 0) {
  connection = new Connection(RPC_URL, {
    commitment: 'processed',
    fetch: coalesceFetch(),
    disableRetryOnRateLimit: true,
    // httpAgent: keepaliveAgent,
  });
} else {
  connection = new Connection(RPC_URL, {
    // httpAgent: keepaliveAgent,
    disableRetryOnRateLimit: true,
    commitment: 'processed',
  });
}

**Comment by yangzongru-jpg** [comment]
why you can comment out httpAgent, is that any problem? because you comment out something......
