### ISSUE TITLE
Stream error: 13 INTERNAL: Response message parsing error: Value is larger than Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by dexbotdev** [jito-labs/mev-bot#6]
ERROR (local/21421): Stream error: 13 INTERNAL: Response message parsing error: Value is larger than Number.MAX_SAFE_INTEGER
    err: {
      "type": "Error",
      "message": "Stream error: 13 INTERNAL: Response message parsing error: Value is larger than Number.MAX_SAFE_INTEGER",
      "stack":
          Error: Stream error: 13 INTERNAL: Response message parsing error: Value is larger than Number.MAX_SAFE_INTEGER
              at ClientReadableStreamImpl.<anonymous> (/Users/shanmugha/testspace/mevbotjito/node_modules/jito-ts/dist/sdk/geyser/geyser.js:67:47)
              at ClientReadableStreamImpl.emit (node:events:513:28)
              at Object.onReceiveStatus (/Users/shanmugha/testspace/mevbotjito/node_modules/@grpc/grpc-js/build/src/client.js:357:28)
              at Object.onReceiveStatus (/Users/shanmugha/testspace/mevbotjito/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:320:181)
              at /Users/shanmugha/testspace/mevbotjito/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
              at processTicksAndRejections (node:internal/process/task_queues:78:11)
    }

**Comment by p0st1t** [comment]
Hello, same error here...

Have you found a solution please?
